=== AkshatShetty101/TA-Coursework/ADS/client/order.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" 
  xmlns="https://www.w3schools.com" elementFormDefault="qualified">


  <xs:complexType name="boot">
    <xs:sequence>
      <xs:element name="id" type="xs:string" maxOccurs="1"/>
      <xs:element name="quantity" type="xs:string" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="orderinfo">
    <xs:sequence>
      <xs:element name="id" type="xs:string" maxOccurs="1"/>
      <xs:element name="personId" type="xs:string" maxOccurs="1"/>
      <xs:element name="bootInfo">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="boot" type="boot" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="orderstore">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="order" type="orderinfo" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== AkshatShetty101/TA-Coursework/ADS/client/order_store.xml
<?xml version="1.0"?>
<orderstore xmlns="https://www.w3schools.com" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="order.xsd">
  <order>
    <id>o1</id>
    <personId>p1</personId>
    <bootInfo>
      <boot>
        <id>b1</id>
        <quantity>2</quantity>
      </boot>
      <boot>
        <id>b4</id>
        <quantity>1</quantity>
      </boot>
    </bootInfo>
  </order>
  <order>
    <id>o2</id>
    <personId>p2</personId>
    <bootInfo>
      <boot>
        <id>b3</id>
        <quantity>4</quantity>
      </boot>
      <boot>
        <id>b4</id>
        <quantity>1</quantity>
      </boot>
    </bootInfo>
  </order>
  <order>
    <id>o3</id>
    <personId>p3</personId>
    <bootInfo>
      <boot>
        <id>b2</id>
        <quantity>1</quantity>
      </boot>
    </bootInfo>
  </order>
  <order>
    <id>o4</id>
    <personId>p1</personId>
    <bootInfo>
      <boot>
        <id>b2</id>
        <quantity>2</quantity>
      </boot>
    </bootInfo>
  </order>
</orderstore>
