=== AkshatShetty101/TA-Coursework/ADS/client/person.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

<xs:complexType name="personinfo">
  <xs:sequence>
    <xs:element name="email" type="xs:string" maxOccurs="1"/>
    <xs:element name="name" type="xs:string" maxOccurs="1"/>
    <xs:element name="password" type="xs:string" maxOccurs="1"/>
    <xs:element name="orders" maxOccurs="1">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="order" type="xs:string" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:complexType> 
    </xs:element>
  </xs:sequence>
</xs:complexType>

<xs:element name="personstore">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="person" type="personinfo" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== AkshatShetty101/TA-Coursework/ADS/client/person_store.xml
<?xml version="1.0"?>
<personstore xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="person.xsd">
  <person>
		<email>abc@gmail.com</email>
    <name>Jamshed Issac</name>
    <password>asdfgh</password>
    <orders>
      <order>123</order>
      <order>456</order>
    </orders>
  </person>
	<person>
    <email>xyz@gmail.com</email>
    <name>Jack Vaidya</name>
    <password>asdfgh</password>
    <orders>
      <order>789</order>
      <order>012</order>
    </orders>
  </person>
</personstore>
